// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ModeloParcial.Models;

public partial class Envio
{
    public int Id { get; set; }

    public DateOnly Fecha { get; set; }

    public string DniCliente { get; set; }

    public string Direccion { get; set; }

    public string PalabraSecreta { get; set; }

    public bool Estado { get; set; }

    public virtual ICollection<DetalleEnvio> DetalleEnvios { get; set; } = new List<DetalleEnvio>();
}